### ISSUE TITLE
Blank page; URL /api/2gather/session gives 404

### ISSUE THREAD

**Issue by AronVanAmmers** [eris-ltd/2gather#27]
Got a local test chain running. After opening http://localhost:3000/2gather/ I'm asked for a user name and fill one in. After that the page stays blank.

In the Chromium developer tools I see 1 error about the url http://localhost:3000/apis/2gather/session giving a 404.
![screenshot Chromium](https://cloud.githubusercontent.com/assets/1123543/6426625/08d9df38-bf65-11e4-81bc-f0e745474838.png)

**Comment by compleatang** [comment]
yes. we should have the rest of the UI hooked up by early week upcoming. right now the back end is solid and the ui is mostly done, just have to finish hooking them together.

**Comment by dennismckinnon** [comment]
The cause has been found.

in 2gather/models/TwoGatherApi.js the line 

`var COMMITTING = false` needs to be set to true. Fix will be pushed tomorrow.
