### ISSUE TITLE
Error during docker compose

### ISSUE THREAD

**Issue by vijayee** [eris-ltd/2gather#37]
Getting this message after `sudo docker-compose -f spec/fig_testing.yml up`
`fig.yml is deprecated and will not be supported in future. Please rename your config file to docker-compose.yml

client and server don't have same version (client : 1.14, server: 1.12)`

**Comment by compleatang** [comment]
thanks. the deprecation warning is a temporary thing. we'll update the filenames shortly. `fig` was very recently renamed to `docker-compose` so they are flagging the `fig.yml` 's at this point for deprecation. when you add the `-f` flag though then the name doesn't really matter. This would only matter when they actually don't read `fig.yml` && when you just do `docker-compose up` without explicitly stating the file. 

but the second line is more troubling. we have not tested our system on docker versions < 1.3 so we're not sure if they work or not. Is the decerver booting or does it flame out after that `client and server` mismatch error? If it flames you then you may want to [update your docker](https://docs.docker.com/installation/). 

will leave open to make sure that this works for you.

**Comment by compleatang** [comment]
closing this for now. let us know if this reappears.
