### ISSUE TITLE
XHR Error on video search

### ISSUE THREAD

**Issue by Anolith** [eris-ltd/2gather#38]
Hello guys

I installed 2gather without docker. The upload works fine, but when I try to search for videos I get : 

![screenshot from 2015-03-09 09 30 25](https://cloud.githubusercontent.com/assets/3910000/6551833/efedf032-c63e-11e4-8043-deeaecf78216.png)

I have been searching for 2 days and nothing I try works.
Thanks for the help !

**Comment by JakeMuller** [comment]
@Anolith can you check if you still getting this error. I can't seem to reproduce it. Did you use docker-compose to build it?

**Comment by Anolith** [comment]
@JakeMuller I first tried installing 2gather without docker, but installing 2gather with docker-compose worked perfectly and I am not getting this error anymore. thank you
