### ISSUE TITLE
Upload issue on main test chain

### ISSUE THREAD

**Issue by JakeMuller** [eris-ltd/2gather#43]
After logging in with the user session and trying to upload a video by calling verb `POST` to `user/:username/videos` I get a 500 response. The error seems to be with connection to ipfs as per below logs.

```2gather_1 | Error finalizing POST: Post http://localhost:8080/ipfs/: dial tcp 127.0.0.1:8080: connection refused
2gather_1 | [Runtime] 2015/03/15 20:16:35 Error when adding file to ipfs.
2gather_1 | [Runtime] 2015/03/15 20:16:35 RESPONSE OBJECT: {"Body":"Internal error - blockchain transaction not processed.","Header":{},"Status":500}```

This does not happen when on the normal spec chain, only on the main chain.

**Comment by compleatang** [comment]
hmm. here's where the error is: `Post http://localhost:8080/ipfs/` decerver should be trying to connect to `Post http://ipfs:8080/ipfs/`. 

This means that either the docker-compose file does not have the `CONTAINERS=true` environment variable; or you have a very old decerver container (unlikely, but just adding in case others google for this problem); or you are running not in containers and don't have IPFS started.

note that the normal docker-compose file which connects into the test chain does have the proper environment variable set [here](https://github.com/eris-ltd/2gather/blob/master/docker-compose.yml#L11) so I'm not sure what is going on.
