### ISSUE TITLE
no peers on the chain?

### ISSUE THREAD

**Issue by jdevoo** [eris-ltd/2gather#44]
This may be a lack of understanding but would I not start to see uploaded videos from peers on the 2gather test chains after a while? I use start.sh, upload my material to my local IPFS node which renders. I can also modify the view no problem. I just thought that the difference between start and start-test would be me seeing other's uploads.

**Comment by compleatang** [comment]
Yup. That is definitely the difference. Last night I completely screwed up the chain testing some new stuff so I had to reset it, so there are just probably no videos there yet. :)

**Comment by JakeMuller** [comment]
Even if there are videos. They can only be found if you search them by entering a valid username in the search bar at the top. This is according to design.

**Comment by compleatang** [comment]
@jdevoo , @androlo  said he would try to add some videos tonight or tomorrow to the current chain as will I....
