### ISSUE TITLE
Subscriptions span to all users

### ISSUE THREAD

**Issue by JakeMuller** [eris-ltd/2gather#48]
When I subscribe to a specific user, all users in the system get subscribed to that user.

e.g. when GET /users/compleatang it returns all the users I subscribed to. If I unsubscribe from the user, it also removes it for compleatang. Same applies with any other user e.g. users/jdevoo.

**Comment by dennismckinnon** [comment]
Fixed via 203fcd43987ba7104b161285bb2465c6afcb3716
