### ISSUE TITLE
"Low difficulty" installation instructions in the readme are apparently buggy

### ISSUE THREAD

**Issue by nham** [eris-ltd/2gather#54]
I attempted the "Low Difficulty Installation" from the Readme. I'm on  Arch Linux, so I installed Docker from the official repos and Docker-Compose from the AUR. (This latter part doesn't match the instructions in the readme, but I am guessing it doesn't matter. I apologize if it does).

Now we come to the part that is "ultra simple". Executing

    (sudo) docker-compose -f docker-compose-get.yml up

yields

    [Errno 2] No such file or directory: u'./docker-compose-get.yml'

I see there is a "docker-compose-get.yml" file in the git repo however, so even though you did not specify to download this, I'm assuming I need to do that. After doing that and running again I get:

    Couldn't connect to Docker daemon at http+unix://var/run/docker.sock - is it running?
    
    If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

This error message seems to indicate that I need to have some Docker daemon running. But since I have no experience with Docker, I don't know what that is or how to do that. Where have I gone wrong? How can I finish the installation?

**Comment by compleatang** [comment]
Thanks for the issue. We'll add a note about needing the file locally (my apologies for the oversight).

The main issue though with getting docker daemon started should be fixable with:

```
sudo systemctl start docker
```

via Dockers documentation [here](http://docs.docker.com/installation/archlinux/)

If that doesn't fix it let us know and we'll keep investigating. None of us are Arch users but hopefully we can get you going!

**Comment by nham** [comment]
Thanks. Still getting the same error, but I'll poke around and see if I can figure out what the correct value for DOCKER_HOST should be.

**Comment by compleatang** [comment]
Please let us know if you figure out the error and we'll update the Readme accordingly.

**Comment by nham** [comment]
Ahh, I'm an idiot. I needed to run `docker-compose` with `sudo`. Still, adding these two steps to the README would be helpful I think

 - download `docker-compose-get.yml`
 - ensure the docker daemon is running after installation

Thank you very much for the help! Sorry for the trouble.

**Comment by compleatang** [comment]
No trouble at all. Always great to have a fresh pair of eyes on the Readmes!
